# Generated by Django 6.0.8 on 2026-09-07 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=8, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=80, verbose_name='Слаг')),
                ('short_description', models.CharField(blank=True, max_length=128, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('city', models.CharField(default='Рязань', max_length=64, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('housing_type', models.CharField(choices=[('apartment', 'Квартира'), ('studio', 'Студия'), ('apartments', 'Апартаменты'), ('house', 'Дом'), ('room', 'Комната')], default='apartment', max_length=16, verbose_name='Тип жилья')),
                ('deal_type', models.CharField(choices=[('rent', 'Аренда'), ('sale', 'Продажа')], default='rent', max_length=8, verbose_name='Тип сделки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена')),
                ('rooms', models.PositiveIntegerField(default=1, verbose_name='Комнат')),
                ('guests', models.PositiveIntegerField(default=2, verbose_name='Гостей')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь, м²')),
                ('image', models.ImageField(blank=True, null=True, upload_to='housing/', verbose_name='Главное фото')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Отзывов')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('approved', 'Опубликовано'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=10, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('amenities', models.ManyToManyField(blank=True, related_name='housings', to='housing.amenity', verbose_name='Удобства')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_listings', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Жильё',
                'verbose_name_plural': 'Жильё',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Заезд')),
                ('check_out', models.DateField(verbose_name='Выезд')),
                ('guests', models.PositiveSmallIntegerField(default=1, verbose_name='Гостей')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение хозяину')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('declined', 'Отклонена'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Решение принято')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Решение принял')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Гость')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='housing.housing', verbose_name='Жильё')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HousingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='housing/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='housing.housing', verbose_name='Жильё')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-is_cover', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='housing',
            index=models.Index(fields=['status', '-created_at'], name='housing_hou_status_0c9e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='housing',
            index=models.Index(fields=['deal_type', 'price'], name='housing_hou_deal_ty_de18ab_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'check_in'], name='housing_boo_status_b1a751_idx'),
        ),
    ]
